#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#!^+f12::
Suspend,Toggle
return

#F1::return
#b::return
#c::return
#d::return
#e::return
#f::return
#h::return
#i::return
#k::return
#l::return
#m::return
#o::return
#p::return
#q::return
#r::return
#s::return
#t::return
#u::return
#v::return
#+v::return
#w::return
#x::return
#z::return
#,::return
#Pause::return
#^f::return
#+m::return
#*1::return
#*2::return
#*3::return
#*4::return
#*5::return
#*6::return
#*7::return
#*8::return
#*9::return
#*0::return
#Tab::return
#+Tab::return
#^Tab::return
#^b::return
#Up::return
#Down::return
#Left::return
#Right::return
#Home::return
#+Up::return
#+Down::return
#+Left::return
#+Right::return
#Space::return
#^Space::return
#Enter::return
#+.::return
#.::return
#/::return
#!Enter::return
#+::return
#-::return
#Esc::return
#NumpadAdd::return
#NumpadSub::return
#NumpadDiv::return